### ISSUE TITLE
Provide an activity indicator in the colony/user creation wizards for DDB operations before and after transactions

### ISSUE THREAD

**Issue by JamesLefrere** [JoinColony/colonyDapp#1408]
### Note 
A temporary solution for this was introduced with https://github.com/JoinColony/colonyDapp/pull/1632. We currently still store the loading status in the transaction record.

### Story

Two user stories:

* As a *user creating a colony*, I want to *see a visual indicator of activity/loading*, so that *I know I should wait for it to finish*

* As a *new user registering a username*, I want to *see a visual indicator of activity/loading*, so that *I know I should wait for it to finish*

### Description

During the colony/user creation wizards, there is an activity indicator for pending transactions, but there is no indicator of other async operations (e.g. for the DDB) before/after these transactions. It's important that the indicator remains visible until all async activity is finished, because otherwise the user has no feedback that they're waiting for something to finish; they might leave the wizard or refresh the page, leading to frustration.

### This issue is complete when...

* For both the colony/user creation wizards:

- [ ] The activity indicator for the `TransactionStatus` component is shown during any and all async waiting
- [ ] The indicator is hidden when async waiting finishes (either successfully or unsuccessfully)
- [ ] The indicator is shown when the transaction is pending (current behaviour), given no other async waiting
- [ ] The indicator is hidden when the transaction is not pending (current behaviour), given no other async waiting

### Suggestions

* It's probably a good idea to keep the transaction state separate from other async actions that relate to them; i.e. either adding an extra transaction status, or keeping the transaction as `PENDING` while other async activity finishes would probably lead to some confusion and unintended side effects. Perhaps component state would be a more suitable starting point.
* Maybe consider whether the name of the components needs to change?

### Subtasks

- [ ] Create a prop (e.g. with component state) which indicates either a transaction is pending, or async activity is in progress related to that transaction, in the context of the wizard
- [ ] Pass down a prop to the `TransactionStatus` component
- [ ] Adjust the `TransactionStatus` component such that it shows the indicator with the given prop

During the colony/user creation wizards, there is an activity indicator for pending transactions, but there is no indicator of other async operations (e.g. for the DDB) in between these transactions. 

Suggested solution: Use the same indicator as the transaction for that step.
