### ISSUE TITLE
Allow tasks to be created before funding the colony

### ISSUE THREAD

**Issue by itspatch** [JoinColony/colonyDapp#1497]
### Story

As a *user who just created a task*, I want to *be able to create a task before minting a token or funding a colony*, so that *I can choose which order to set up my colony in.*

### Description

Currently, we are missing the designs for adding tasks below the "mint tokens" empty state on the colony home screen. Below are the designs if a user adds a task to the empty state.

So while the colony has 0 balance of any tokens, they will see the "mint / fund colony" on the home screen. But as soon as they either mint tokens OR fund the colony with a different token, this goes away.

Additional slack convo here: https://joincolony.slack.com/archives/C0YNG3M8B/p1562763319184800 

### Design

[Figma link](https://www.figma.com/file/CGSZdfl2KbfKvG30jnoKSmtn/Onboarding?node-id=1373%3A22031)

If a colony created their own token.
![Mint Tokens, Task Created](https://user-images.githubusercontent.com/19378807/61080728-8faa2000-a3da-11e9-9d0e-ac3e5c5ff0ef.png)

If a colony brought a token
![Send Token, Task Created](https://user-images.githubusercontent.com/19378807/61080918-edd70300-a3da-11e9-8c20-6d33562ce141.png)

### This issue is complete when...

- [x] The 'new task' button on the colony home view is visible/enabled (if the user has the permissions), whether there is a token balance or not
- [x] Tasks can be created whether there is a token balance or not (this is probably the current behaviour already, but this is distinct from the button visibility)
- [x] The task list is visible under the 'mint tokens' form if no token balance exists
- [ ] The 'one small task for man' button is still visible/enabled when there are no tasks (i.e. retain this current behaviour)
- [ ] The 'one small task for man' button is not visible when there are tasks (i.e. retain this current behaviour)

### Suggestions

None yet

### Subtasks

- [ ] Adjust `ColonyHome` logic for showing 'new task' button
- [ ] Adjust `ColonyHome` logic for showing 'one small task for man' button
- [ ] Adjust `ColonyHome` logic for showing tasks list (if necessary)
