### ISSUE TITLE
Add fallback UI for USD gas amount estimations that time out

### ISSUE THREAD

**Issue by itspatch** [JoinColony/colonyDapp#1599]
### Story

* As *a user sending a transaction*, I want to *see that my transaction is ready to send if the USD amount could not be found*, so that *I do not wait for an estimation that won't show up*.

### Description

I noticed that there is usually an endless spinner on the gas station when we cannot retrieve the USD amount. 

### Design

Here are two designs that can be used for a timeout call if we cannot get the USD amount. 

![TimeOutUSDAdmin](https://user-images.githubusercontent.com/19378807/61673316-f96cd880-acbc-11e9-90da-8c4c042fe527.png)
![TimeOutUSDGas](https://user-images.githubusercontent.com/19378807/61673317-fa056f00-acbc-11e9-88fd-c960dbd01a05.png)

Current spinners in the dApp.

<img width="1412" alt="Colony" src="https://user-images.githubusercontent.com/19378807/61673626-3f766c00-acbe-11e9-8151-a9a3422f7521.png">

<img width="683" alt="Colony_and_Downloads" src="https://user-images.githubusercontent.com/19378807/61673652-5ae17700-acbe-11e9-9cb1-12c6190865aa.png">

### This feature is complete when...

- [ ] A proper timeout mechanism is in place for getting the USD amount for a transaction in the gas station _(this may already be in place)_
- [ ] A proper timeout mechanism is in place for getting the USD amount for a token card _(this may already be in place)_
- [ ] The fallback UI is shown when getting the USD amount for a transaction in the gas station times fails
- [ ] The fallback UI is shown for a token card when getting the USD amount fails
- [ ] The fallback UI is shown for a token payout when getting the USD amount fails

### Suggestions

* Question: what should the default state be? (before fetching)

### Subtasks

* No subtasks yet
