### ISSUE TITLE
Show colony address on colony home view

### ISSUE THREAD

**Issue by itspatch** [JoinColony/colonyDapp#1605]
### Story

As a *non-admin funding a colony*, I want to *see the colony address on the home screen*, so that *can copy it and send it funds*

### Description

Add the colony address to the colony home so that any user can find that address to send it funds. 

On the colony home screen, there should be a new section for the colony address and a way to copy that address. 

### Design

![Colony Address](https://user-images.githubusercontent.com/19378807/61719799-95d1c200-ad33-11e9-90a4-b1650f79728c.png)

[Figma link](https://www.figma.com/file/CiOvNosDu3XpJxBK8sUf6jLM/Colony-Home?node-id=1598%3A0)

### This issue is complete when...

- [x] The colony address is visible on the colony home view as per the design
- [x] The address is shortened and copyable

### Suggestions

* Use the `CopyableAddress` component

### Subtasks

- [x] Ensure colony address prop is available in `ColonyMeta` component
- [x] Add i18n for 'Colony address'
- [x] Render colony address in `ColonyMeta` component
