### ISSUE TITLE
Add inbox popover

### ISSUE THREAD

**Issue by Karol-colony** [JoinColony/colonyDapp#1654]
### Story

As a _worker assigned to a few tasks_, I want to _see who has mentioned me in a comment_, so that _I can easily access the right task without switching the context_. 

### Description

1. Clicking the envelope icon in the top right area opens up a popover with a list of notifications.
2. The blue vertical stripe shows unread notifications (if this is super complex, it can be a taco, or can be shipped later, but highly recommended)
3. Ignore the pink stripe for now – they are for time-dependent notifications (like a due date, or time required to do something). 
4. Notice the pink dot – it shows up if new notifications appear. It disappears after opening the popover regardless if someone opened the notification or not. We do not show any numbers there. Opening the popover means that notifications are read. 
5. When the popover is opened, the envelope icon has a blue colour.
6. Clicking "see all" opens a new page with a fullscreen view of the notifications. 

### Design 

[Figma link](https://www.figma.com/file/OD53CoZpRKVqDdKsMYGldko8/Inbox?node-id=194%3A0)

![image](https://user-images.githubusercontent.com/20819402/62423883-29f24080-b6c7-11e9-939c-afb27e844d01.png)

### This issue is complete when...

- [x] The inbox icon has a red indicator when there are unread inbox items
- [x] The inbox icon opens a popover with the inbox content
- [x] The inbox icon is active when the popover is open
- [x] The notifications are marked as read when the popover is opened
- [x] The inbox content is adjusted to fit in the popover according to the design (if necessary)
- [x] A 'see all' button is added to the bottom of the inbox content, which links to the full-screen view
- [x] 🌮The content of the popover is visibly limited to 4 inbox items (with vertical overflow scroll)

### Subtasks

- [x] Add unread indicator to icon
- [x] Define popover
- [x] Trigger popover with icon and mark icon as active
- [x] Adjust popover style if necessary
- [x] Add 'see all' button
- [x] 🌮Limit the content to 4 visible items and provide vertical scroll for overflow

### Suggestions

* From @rdig : we need to bear in mind that colony/user addresses (when a label isn't available) will need to be shortened. This might cause visual issues.
* Also from @rdig : Look at the network health/gas station popovers. It might be possible to extract these components into something more generalised and use them for this.

It is more about checking the style of the inbox popover on figma.

 ~Fullscreen view is a taco or can be part of a different task (iceboxed for the future).~ The fullscreen view is already implemented AFAICT _—James_

The "X" icon to remove the notification from the list is a taco (see description on figma).
