### ISSUE TITLE
Support editing of domain names

### ISSUE THREAD

**Issue by Karol-colony** [JoinColony/colonyDapp#1655]
### Story

As _an admin of a colony_, I want to _change a domain name_, so that _it can be labelled differently_. 

### Description

Editing the domain is accessible from colony settings. The user has to have the required permissions to add domains or change a domain name (either root or administrative in colony, or for a certain domain). 

The edit domain button shows up on hovering over domain name (the whole 'card') as on design. 

### Design

[Figma link](https://www.figma.com/file/L6scZfliLKnDt95nwan4jwzg/DLP-DLF?node-id=1137%3A33) - the bottom page "Edit Name"

![image](https://user-images.githubusercontent.com/20819402/62424263-b05d5100-b6cc-11e9-9f3f-9fca403dcb82.png)
![image](https://user-images.githubusercontent.com/20819402/62424265-b8b58c00-b6cc-11e9-816c-426f958d9c23.png)

### This issue is complete when...

- [x] An 'edit name' link is visible on domains (when the user has the required permissions)
- [x] Clicking on the link opens a modal with a form to edit the domain name
- [x] Submitting the form changes the domain name

### Subtasks

- [x] Add 'edit name' link and show it based on permissions (perhaps just `canAdminister` until we have DLP?)
- [x] Add 'edit domain name' form and trigger it from the link, including `react-intl` dialogue
- [x] Add DDB event to edit domain name
- [x] Add new permission in the access controller (copy the old one)
- [x] Change event reducer to set the name to the final value
- [x] Add command to edit domain name
- [x] Add redux actions and saga to call the command
- [ ] Make sure that change is propagated in the app state

### Suggestions

* Ensure the domain name is validated and presented in the same way as when adding domains.
* Side-fix that might help: check the task feed for the '#' that should not be there anymore
