### ISSUE TITLE
Interactive user avatar popovers

### ISSUE THREAD

**Issue by Karol-colony** [JoinColony/colonyDapp#1656]
### Story

As a _task owner_, I want to _double-check if the assignee wallet address is the right one_, so that _I feel more confident completing a task_.

### Description

1. The general idea is to make avatars and usernames clickable (task UI and colony home) to copy the wallet address quickly. It is not convenient now. 
2. On figma, there is more detailed specification which areas are part of this task. It is not a global change. Edge cases are also included (f.e. if there is no username, but only the wallet address).
3. On click, the popover appears; on clicking off (i.e. somewhere on the background) it hides. It should be possible to copy the wallet address and highlight text inside a popover. It would be nice to add a subtle ease-in-out transition. 

### Design

[Figma link](https://www.figma.com/file/IsTzagr0TvzEMf3nwIcTthLm/Task-Workflow?node-id=4448%3A0)

![image](https://user-images.githubusercontent.com/20819402/62424716-f3222780-b6d2-11e9-9e2e-6db0c57211f1.png)

### This issue is complete when...

- [x] The `UserInfo` component is replaced with this one
- [x] The user display name is shown when available (no biggie if not)
- [ ] The username is shown when available (no biggie if not) and links to the user profile
- [x] The user address is always shown and is copyable
- [ ] 🌮The popover is opened on hover (but this is quite complicated, so don't worry too much)

### Suggestions

* We should come up with a more meaningful name for the component (we like the sound of `InfoPopover`)
* We should open another issue to do this for colonies

### Subtasks

- [x] make InfoPopover work in `TaskFeedEvent`
- [x] make InfoPopover work in `UserInfo` component
