### ISSUE TITLE
Add links to inbox item content

### ISSUE THREAD

**Issue by JamesLefrere** [JoinColony/colonyDapp#1659]
### Story

As a user viewing notifications, I want to go to the subject/context (colony/task) of the notification, so that I can act on it.

### Description

For the inbox items, these are currently textual, but we ideally want to have links to colonies/users/tasks. 

### Design

[Image](!https://user-images.githubusercontent.com/20819402/62423883-29f24080-b6c7-11e9-939c-afb27e844d01.png)

### This issue is complete when...

- [ ] Each notification type has links where appropriate
- [ ] The style of the link matches the design

### Suggestions

* There are a number of props that need to be present for different notification types (e.g. colony address, colony name (for the link), user address, username, task ID). Make sure these are passed down or inferred in a simple way.
* It's _possible_ that events might need changing (if the data isn't all there?) which might necessitate query/command changes (worse case scenario!)

### Subtasks

- [x] Pass down the relevant props to each inbox item component
- [x] Create links for each notification type
- [ ] Adjust style if necessary
