### ISSUE TITLE
Add Seen/Unseen behaviour to inbox notifications

### ISSUE THREAD

**Issue by collinvine** [JoinColony/colonyDapp#166]
# Jobs Story
When viewing my Inbox notifications
I want to see which notifications have been read and which ones haven’t been
So that I can take action on the things that still need my attention

# Specs

![inbox.png](https://images.zenhubusercontent.com/56a59e4c6caf56c9d38bdedc/60672a96-819d-454f-beb7-567a955f6681)

This is functionality that was already added in the beta, and we want it brought over for the mainnet MVP.

See this beta issue for more: https://github.com/joincolony/colonybeta/issues/1432

**TODO**
Notification events:
- [ ] Add blue vertical bar for unseen Notifications events
- [ ] blue vertical bar disappears on click

Action events:
- [ ] Add red vertical bar for unseen Action events
- [ ] Red vertical bar disappears only when the Action has been complete
