### ISSUE TITLE
Refactor colony roles

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyDapp#1694]
### Story

As a Colony developer I need to be able to query the roles a user has more granularly, and per domain.

### Description

> tl;dr - refactor get roles query/saga/reducer to fetch and store roles per colony/user/domain combo; refactor existing role selectors to proxy the `OldRoles` behaviour based on new redux state

A while ago the roles that can be set for users in a Colony changed from the old `Admin` and `Founder` to a new set, which are also **domain specific**:

- `Recovery`
- `Root`
- `Arbitration`
- `Architecture`
- `ArchitectureSubdomain`
- `Funding`
- `Administration`

Right now, because the whole dApp was based on the old roles, we just proxy the new roles to the old ones when we fetch them, and continue storing them in redux like we did before.

But we now are beginning to transition towards using the new roles in the dApp, so we need to store the roles according to what is actually being fetched: the role that a user has, in a specific domain, in a specific colony.

### Design

All technical for this first issue I'm afraid!

### This issue is complete when...

- [ ] The `colonyRolesFetch` saga (or rather, the query it uses) returns data containing roles that users have in specific domains (the success action has data in new the format) - it will still fetch this from contract events in the same way it does currently
- [ ] Role data is stored in redux according to the new data which is fetched (the reducer has been updated for the new success action from the fetch saga)
- [ ] The existing `colonyRolesSelector` proxies the redux data to return data of the old format (if the user has all the roles that the `OldRoles` contract would set, then they are admin/founder) - this is done to prevent breaking existing components which may be needed for testing the new stuff
- [ ] An additional action/saga/query has been created which fetches roles for a user in a specific domain of a colony using `hasUserRole` (will be used for ensuring fresh data), and which is handled by the colony roles reducer

### Suggestions

* It's definitely up for debate, but here's what the redux state could look like per colony. It's keyed this way because we definitely want to be able to fetch all the users with roles in a domain, but I couldn't think of cases where we would want all the domain a user has roles in (at least not yet). But even if we do need that, we could set up a reverse mapping in the future.
```
{
  [domainId]: {
    [userAddress]: {
      [roleId]: boolean
    }
  }
}
```

### Subtasks

- [ ] Populate this if you think you need it 😄
