### ISSUE TITLE
Add new colony role selectors

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyDapp#1696]
### Story

As a Colony developer, I want to be able to select granular user roles from the redux state, as well as the effective permissions a user has in a specific domain as a result of any parents.

### Description

> tl;dr - new permissions selectors for whether a user has a (new, granular) role in a specific domain, and one for that specific domain or its parents (this could be an option passed to the selector)

Now that we've got a fancy new redux state for permissions (#1694), we need to be able to select them! In some cases, we want to know the roles which have been set for a user in a specific domain only, but other times we care about the effectual _permissions_ that a user has - that is the result of the roles that have been set for the user in that, or any parent domains. As a result, we're going to want two selectors (or an option on a single selector).

### Design

Still just technical!

### This issue is complete when...

- [ ] A selector exists which gives me all the users with roles in a specific domain, and what roles they have in that domain (and only that domain), and another for that domain and all parents (could be an option to the selector)
- [ ] A selector exists which gives me the roles for a specific user in a specific domain (and only that domain), and another for that domain and all parents (could be an option to the selector)

### Suggestions

* For the _that domain and any parents_ selector, you'll need some way of working out what the parents of the domain being selected for are. Right now, we only have one level of domains under the root, so all non-root domains are direct children of it. That means you could just select for that domain, and root. But in the future we will have multiple levels, so for future-proofing, I suggest to refactor domains in redux state to also store `parentDomainId`, and use that in the selector.
* The _that domain and any parents_ selectors could also be done in a utility function or hook if you think they don't belong in a selector (could be a bit complicated for a selector)

### Subtasks

- [ ] Populate this if you need
