### ISSUE TITLE
Add granular domain-specific role setting

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyDapp#1697]
### Story

As a Colony developer, I want to be able to set a specific role for a certain user in a specific domain of a colony.

### Description

> tl;dr - new set permission saga which sets the roles of a user in a specific domain - accepts map of role to boolean and diffs with existing roles to determine which need updating with txs

Right, so now we can query permissions according to the new roles (#1696), but we're still setting them exclusively using the `OldRoles` extension contract. Now we need to be able to set the individual new roles.

We're going to want a new action/saga which accepts a `colonyAddress`, a `domainId` within that colony, and a map of `{ [roleId]: boolean }`. The saga should then work out which of those roles already apply to the current user, and create a group of transactions to make up the difference. It should also check to make sure that the current user (the one who's logged in, calling this function) has the appropriate permission to be calling this function - if not, throw a descriptive error.

Additionally, we're going to need a flag that we can set for a user's permissions per domain of a colony while there are transactions in progress for altering them. The saga should set this flag when the transaction group starts, and remove it once they're all done.

### Design

Still no designs here!

### This issue is complete when...

- [ ] You can set individual roles for a user in a specific domain!
- [ ] The redux state has some kind of pending flag set for that user's permissions in that domain while the transactions are happening

### Suggestions

* This _pending_ flag could be put alongside the permissions, so the redux state would be like `{ [domainId]: { [roleId]: boolean, pending: boolean } }`

### Subtasks

- [ ] Populate if you need!
