### ISSUE TITLE
Create DLP permissions list components

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyDapp#1699]
### Story

As a user I want to be able to see a list of users with roles for each domain of my colony along with which roles they have, so that I have greater control over who has permissions in my colony.

### Description

It's time for some components to be made! This issue is for the permissions list, which will have a filter dropdown to select the domain, and then display a list of all users who have permissions in that domain, along with what roles it is they have permission for.

This issue doesn't include full wiring, however you should definitely consider what the data will look like that will be provided to these components (or fetched by them).

### Design

[Figma link](https://www.figma.com/file/L6scZfliLKnDt95nwan4jwzg/DLP-DLF?node-id=998%3A26740)

![image](https://user-images.githubusercontent.com/7497084/62785532-7d023400-bac9-11e9-832a-44c1b26afc86.png)

In cases where the user doesn't have a profile, we use a blockie and just don't show a name or username. The address is just shifted up in their place.

Upon clicking an item in the list, when wired it will open the permissions add/edit dialog.

Users with the root role permission should be shown at the top of the list. The order of the rest of the list doesn't matter.

There should be support for a "pending" state for users whose permissions are in the process of being altered.

![image.png](https://images.zenhubusercontent.com/5b1e8830b6bfa875f7c71f6b/eb20fbdf-0eb1-41aa-9997-fb66fba0cd3b)

### This issue is complete when...

- [ ] A permissions list item component has been created according to the design - this should fetch user info (since we already have this available, no need to wait for separate wiring) but the roles info can be a mock for now
- [ ] The colony admin permissions tab contains a filterable list of permission list items! Probably all mock data for now
- [ ] Users with root role permission are shown at the top of the list

### Suggestions

* You might want to use some mock data for these components, but keep the committed mocks to a minimum, and also easy to remove! They won't be around for long 😄 also carefully consider the structure of that data, it should at least very closely match what the real data will be like

### Subtasks

- [ ] ???
