### ISSUE TITLE
Wire DLP permissions list

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyDapp#1708]
### Story

As a colony admin, I want to see who has what roles in a certain domain of my colony, so that I can better administer that colony.

### Description

So by this point we have the component for the DLP permissions/role list done and we want to fill it with real data. This should just be a matter of connecting the dots that already exist.

If a user's roles for the selected domain are pending, they should be shown with the pending indicator.

### Design

None here!

### This issue is complete when...

- [ ] The permissions tab loads with the root domain selected by default
- [ ] A list of users with roles is shown for the selected domain
- [ ] Changing the selected domain causes the data shown to change to that of the selected domain

### Suggestions

* Some wiring should have already been done in the component issue

### Subtasks

- [ ] ???
