### ISSUE TITLE
Create DLP add/edit role dialog component

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyDapp#1709]
### Story

As a colony admin, I want to be able to edit the roles for a user in a certain domain of my colony, so that I can control who has permissions.

### Description

This is an interesting dialog component. We're going to want to be using it for both adding new permissions to a user, as well as editing existing roles. What the component displays varies based on how it was opened, and also based on the permissions of the user interacting with it.

### Design

[Figma link](https://www.figma.com/file/L6scZfliLKnDt95nwan4jwzg/DLP-DLF?node-id=998%3A24864)

We have an added link in the sidebar "Add Role", which when clicked will open the dialog.

![image.png](https://images.zenhubusercontent.com/5b1e8830b6bfa875f7c71f6b/743e3074-c3e8-4f47-8abe-942e05913163)

You can also access the dialog by clicking on a user in the list who already has a role. The user will already be selected in the dialog, and the field will not be editable. The dialog title should change accordingly.

![image.png](https://images.zenhubusercontent.com/5b1e8830b6bfa875f7c71f6b/fdb82093-951d-4a03-b83d-857a1beba0fd)

Checkboxes should be populated with the permissions the selected user already has. Checkboxes should be disabled if the current user doesn't have permission to change them in this domain. The arbitration role should be always disabled with "Coming soon".

### This issue is complete when...

- [ ] Clicking "Add Role" in the sidebar opens the add/edit dialog in the "add" configuration
- [ ] The dialog features a user picker (populated with users currently in state)
- [ ] Dialog is disabled if opened in "edit" configuration
- [ ] Dialog returns/dispatches/something an object ~`{ colonyAddress, domainId, roles: { [roleId]: boolean } }`

### Suggestions

* Can probably use a `DialogActionButton` with fake actions for now

### Subtasks

- [ ] ???
