### ISSUE TITLE
Wire DLP add/edit roles dialog

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyDapp#1710]
### Story

As a colony admin, I want to be able to edit the roles of a user in a certain domain of my colony, so that I can control what permissions users have in my colony.

### Description

Time to wire up this dialog! We will already have the saga and actions by now to dispatch, and also the selector for the data about which roles a user has.

When selecting the user from the picker (or when the dialog is opened with a user already selected), we should dispatch the action to refetch the roles data for that user in the selected domain to ensure we have fresh data (this should be done regardless - TTL of zero).

When selecting the data for what roles the selected user already has, we should use the selector that only selects roles/permissions in that specific domain (not including parent domains). When we select the data for whether the current user is allows to give/remove certain permissions in the domain, we should include parent domain roles too.

Submitting the form should dispatch the action to call the saga which diffs the selected roles with those that the user already has in that domain, and create transactions accordingly. This will update the state of that user's roles to pending (which shows the pending indicator on the permissions/roles list).

We also need to make it so that clicking a user in the permissions list causes the edit roles dialog to appear with the appropriate data pre-filled.

### Design

No more designs for this!

### This issue is complete when...

- [ ] Clicking on a user in the permissions list opens the edit roles dialog with that user already selected
- [ ] The roles that a user has are checked accordingly
- [ ] Checkboxes are disabled if the current user is unable to change that role in that domain
- [ ] Submitting the form causes transactions to be created and the user's permissions set to pending in the list

### Suggestions

* 🤷‍♀️

### Subtasks

- [ ] ???

**Comment by karolinkas** [comment]
This one will be merged together with #1770.
