### ISSUE TITLE
Refactor colony token balances

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyDapp#1768]
### Story

As a Colony developer, I want to differentiate between the different funding pots (domains) where my funds are allocated, so that I have a greater overview of my domain-specific budgets.

### Description

This issue is the start of the group of "phase 2", in which we add the ability to move funds between different domain funding pots. In order to do that, we first need to have the distinction between different domain pots where token balances are held.

Token balances should be stored in state per domain pot. The new state could look something like `{ [domainId: number]: { [tokenAddress: Address]: BigNumber } }`. The saga which fetches token balances should be changed to also include a `domainId` in its params. Any places in the dApp which currently fetch colony token balances should use the root domain as a default.

### Design

Here's [the Figma](https://www.figma.com/file/L6scZfliLKnDt95nwan4jwzg/DLP-DLF?node-id=998%3A27269) for what we're aiming for with this phase. Give it at least a glance over 😄 

### This issue is complete when...

- [ ] Refactor colony token balances reducer to take a `domainId` and store using this
- [ ] Refactor colony token balance fetch saga/actions to include `domainId` as params, fetch token balance for just that domain's pot
- [ ] Refactor any existing uses of the colony token balance fetcher/selector to use root domain

### Suggestions

* ???

### Subtasks (optional)

- [ ] ???
