### ISSUE TITLE
Create a new task workflow + empty state design

### ISSUE THREAD

**Issue by itspatch** [JoinColony/colonyDapp#177]
# Jobs Story
When I'm an admin of a colony
I want to create new tasks
So I can create work for contributors

# Specs
## Designs
**New Task button**
![macbook pro 4 13](https://user-images.githubusercontent.com/19378807/43616396-313fa20a-9671-11e8-8ba7-e3a656e475b1.png)

**Empty state for task creator**
![task empty state](https://user-images.githubusercontent.com/15755488/46898284-0ced3800-ce3d-11e8-8e0d-cdaf96bb3f65.png)

**Empty state for non-task creator**
[Figma link](https://www.figma.com/file/IsTzagr0TvzEMf3nwIcTthLm/Task-Workflow?node-id=2244%3A0&viewport=2477%2C835%2C1.03981)

### Permissions

- [x] only admins and the colony owner can see and click the `New Task` button
- [x] only the task creator can see the `Details` button
- [x] only the task creator can see and interact with the `Add +` buttons
- [x] only the task creator can see the `Close task` button
- [x] other users see a `Request to work` button instead of the details button

### Btn: On click
Once the button on the Colony Home page is clicked, it opens the empty state of the new task.

- [x] add click listener and create a new task when clicked

### Task Anatomy: Empty state, Task Creator
![task anatomy](https://user-images.githubusercontent.com/15755488/46911485-f1079600-cf11-11e8-8e1c-e03d1c1975b4.png)

- [x] Add back to Colony icon + text with copy: "Back to Colony" _bonus points for adding the colony's name!_
- [x] Add button with default copy as "Close Task"
- [x] Add `Assignment and Funding` section
    - [ ] Add unassigned worker avatar icon
    - [ ] Add "Unassigned" placeholder in input field
    - [ ] Add funding section with placeholder copy of "Funding not set"
    - [ ] Add `Details` button; only the task creator can see this
- [x] Add task detail section
    - [ ] Task title placeholder copy is "Task title"
        - [ ] The character limit for the task title is 90
    - [ ] Task brief placeholder copy is "Description"
- [x] Add task property section with Domain, Skill, and Due Date components
    - [x] Each property should have an `Add+` button next to the text label; only admins can see and click
- [x] Add Comment section
    - [ ] Add comment box with placeholder copy = "Leave a comment" 
    - [ ] Add new file uploader icon
    - [ ] Add `Comment` button

_Note: the functionality of the selectors will be spec'd out in other issues._

Here's how it looks when filled out:

![task screen filled](https://user-images.githubusercontent.com/15755488/46910707-d1ff0900-cefd-11e8-9622-992824b4de61.png)

### Empty state for other users
The above is how it looks for the task creator. For other users, this is how it looks:

![empty state other users](https://user-images.githubusercontent.com/15755488/47178672-c9794a80-d2d0-11e8-8407-f22c828e71d0.png)

- [x] add a `Request to work` button instead of the `Close task` button
- [x] do not display the `Add +` buttons
- [x] do not display the `Close task` button
