### ISSUE TITLE
Add move funds between pots dialog

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyDapp#1780]
### Story

As a colony admin, I want to be able to move funds between domain pots, so that I have greater control over where funds are allocated.

### Description

This issue is the main event of the DLF/P phase 2 work! In this, we're adding the dialog component which allows selecting a "from" and "to" domain, as well as entering an amount and token. Submitting the dialog will dispatch the action created in #1779 to create the actual transaction.

Since we already have all the means to wire this thing up, we'll include that here too. The domain pot amounts for the selected token should be displayed below the domain dropdowns. If ETH is selected, then the USD conversion should also be shown (as in Figma).

Domains for which the current user does not have the effective funding role should be shown as greyed out in the domains dropdown, along with a tooltip. Form validation should be run to check that the selected from domain has enough funds to transfer the entered amount.

A "Move funds" button should be added to the admin tokens tab sidebar to open this dialog.

🌮 The dialog should accept a "to domain" as a param when opening, and should be opened with the currently selected domain preselected (or nothing selected if the user does not have permission.

### Design

Dialog: [Figma link](https://www.figma.com/file/L6scZfliLKnDt95nwan4jwzg/DLP-DLF?node-id=998%3A27269)

![image](https://user-images.githubusercontent.com/7497084/64004077-de885200-cb0d-11e9-8ebf-077aa63ebd30.png)

![image](https://user-images.githubusercontent.com/7497084/64004198-12fc0e00-cb0e-11e9-9f4d-3fa6f5fcd26e.png)

![image](https://user-images.githubusercontent.com/7497084/64004660-f8766480-cb0e-11e9-87b1-f927715df614.png)

### This issue is complete when...

- [ ] Dialog exists with from/to dropdowns containing a list of domains, amount input, and token dropdown
  - [ ] Domains in dropdown are disabled if user does not have funding role to move from that pot (⚠️ need clarification on whether to domain also needs funding role)
  - [ ] Domain pot balances for selected token are displayed
  - [ ] Form is validated invalid if not enough funds in from pot
  - [ ] USD amount is displayed if ETH selected
- [ ] "Move funds" button added to colony admin tokens tab sidebar to open dialog
  - [ ] 🌮 Opens dialog with currently selected domain from tokens tab preselected as "to" domain

### Suggestions

* Getting whether the current user has funding permission for each domain shouldn't be too bad, but there might be some trickiness there, especially for greying out domain dropdown items.

### Subtasks

- [ ] ???

**Comment by chmanie** [comment]
One suggestion to make the whole thing much easier is to initially show all domains and when users click on it, we do an async validation and make it either valid or invalid with an appropriate error message.
