### ISSUE TITLE
Colony home screen updates

### ISSUE THREAD

**Issue by sprusr** [JoinColony/colonyDapp#1785]
### Story

As a user viewing a colony, I want a clearer layout, so that I can more easily understand the current state of the colony.

(This is totally a fluff story, sorry)

### Description

There's a whole load of movings around and design changes to be made to the colony home! They can be summed up as:

* `ColonyMeta` has a new layout, and is shifted upwards to overlap with the nav bar
* The domains list has been moved to right below the new colony meta on the left
* The "Contribute" tab is renamed to "Tasks", with the tasks filter moved to within the tab itself (below tabs), and the "New task" button is also moved to within the tab, on the right of the filter
* A currently selected domain breadcrumb is added to the top of the main section of the page (above tabs)

### Design

[Figma link](https://www.figma.com/file/L6scZfliLKnDt95nwan4jwzg/DLP-DLF?node-id=1013%3A43)

![image](https://user-images.githubusercontent.com/7497084/64030385-c3860400-cb46-11e9-89da-f9091cb6e2ad.png)

Description is limited to 88 characters, clicking on "More" will expand to full length.

![image](https://user-images.githubusercontent.com/7497084/64030434-e2849600-cb46-11e9-89f6-3ec21ae3eb25.png)

### This issue is complete when...

- [x] New `ColonyMeta` layout has been created
- [x] Domains list is on the left of the page
- [x] Tabs component has been shuffled about
- [x] Domain breadcrumb has been added to top of page

### Suggestions

* ???

### Subtasks

- [x] Expandable paragraph component needs creating
