### ISSUE TITLE
Domain-specific task creation

### ISSUE THREAD

**Issue by JamesLefrere** [JoinColony/colonyDapp#1801]
### Story

As an admin/founder, I want to create tasks in a given domain, so that the task reflects the context in which it was created.

### Description

Given the permissions checks in #1800 , task creation for a given domain will be limited to users with the admin role in that domain (and the founder). This issue isn't necessarily reliant on those checks being in place, but it goes one step further; tasks will be created in the context of a particular domain such that the domain is defined when the task/store is created. Note that the domain can of course still be changed afterwards (pending permissions).

### Design 

N/A

### This issue is complete when...

- [x] The `TASK_CREATE` action is given a `domainId` payload property
- [x] The `taskCreate` saga passes the domain ID onto the command
- [x] The `createTask` command supports the domain ID
- [x] The `TASK_CREATED` event contains a `domainId` property
- [x] A new data version is created
- [x] Task reducers reflect the changed event
- [x] Backwards-compatibility is provided where necessary
- [x] The currently selected domain (on the colony home view) is passed into the create task actions

### Suggestions

* This issue will probably be easier to complete and test once #1800 is done, but it's not necessarily a pre-requisite.
* The backwards-compatibility should not set a default domain ID for old tasks, so try not to make that a requirement

### Subtasks

None yet
