### ISSUE TITLE
Improve user picker behaviour

### ISSUE THREAD

**Issue by Karol-colony** [JoinColony/colonyDapp#2114]
### Story

Example: As a *user assigning a worker*, I want to *use search bar to find the right username*, so that *I know who match my criteria without any confusions*

### Description (optional, but useful!)
[Figma link](https://the-link-to-the-design-on-figma)

- Let's assume the input is not an address if it is not 40 hex characters prefixed with 0x.
- In which case, we don't need to show this "address format is wrong" error most of the time
- The only time you should see that error is if you have input that starts with 0x or if typed value do not match any username or is not a wallet address

Slack convo: https://joincolony.slack.com/archives/C7HNTLE3T/p1584445797327100

### This issue is complete when...

- [ ] The activity indicator for the `TransactionStatus` component is shown during any and all async waiting
- [ ] The indicator is hidden when async waiting finishes (either successfully or unsuccessfully)
- [ ] The indicator is shown when the transaction is pending (current behaviour), given no other async waiting
- [ ] The indicator is hidden when the transaction is not pending (current behaviour), given no other async waiting

### Suggestions (optional)

* This doesn't have the highest priority right now

### Subtasks (optional)

- [ ] Create a prop (e.g. with component state) which indicates either a transaction is pending, or async activity is in progress related to that transaction, in the context of the wizard
- [ ] Pass down a prop to the `TransactionStatus` component
- [ ] Adjust the `TransactionStatus` component such that it shows the indicator with the given prop
