### ISSUE TITLE
Visual uplift of navigation background

### ISSUE THREAD

**Issue by Karol-colony** [JoinColony/colonyDapp#2115]
### Story

Example: As a *user creating a colony*, I want to *see a visual indicator of activity/loading*, so that *I know I should wait for it to finish*

### Description (optional, but useful!)

If background has gradient, background of top navigation should be transparent, so only a line separate the content. Keep it with gradient for a task UI and suggestions (expection). 

Slack convo: https://joincolony.slack.com/archives/C7HNTLE3T/p1584379142270200

### Design (optional, might not be applicable)

Global:
![image](https://user-images.githubusercontent.com/20819402/77152186-b6574500-6a97-11ea-944c-381034ec21fa.png) (includes home page, settings, program, levels, dashboard, user profile)

2x exceptions: suggestion fullscreen + task UI
![image](https://user-images.githubusercontent.com/20819402/77152250-dedf3f00-6a97-11ea-97d0-2cd34044b0b5.png)

### This issue is complete when...

- [ ] The activity indicator for the `TransactionStatus` component is shown during any and all async waiting
- [ ] The indicator is hidden when async waiting finishes (either successfully or unsuccessfully)
- [ ] The indicator is shown when the transaction is pending (current behaviour), given no other async waiting
- [ ] The indicator is hidden when the transaction is not pending (current behaviour), given no other async waiting

### Suggestions (optional)

* This is very low priority for now

### Subtasks (optional)

- [ ] Create a prop (e.g. with component state) which indicates either a transaction is pending, or async activity is in progress related to that transaction, in the context of the wizard
- [ ] Pass down a prop to the `TransactionStatus` component
- [ ] Adjust the `TransactionStatus` component such that it shows the indicator with the given prop
