### ISSUE TITLE
Create mobile responsive Colony Home Menu

### ISSUE THREAD

**Issue by willm30** [JoinColony/colonyDapp#3476]
## Specification

Relies on issue: https://github.com/JoinColony/colonyDapp/issues/3475

### Story

When navigating from the Colony Home page on my mobile, I would like the main hamburger menu to be mobile-optimised. 

### Description 

This issue addresses screen three of the [Figma design](https://www.figma.com/file/DjVCPq7LpkjEMEfQZtKgBdC1/Style-Guide?node-id=6643%3A9926).

### Design

**Main menu should adapt to mobile screens**
![image](https://user-images.githubusercontent.com/64402732/173377213-45075d2a-2016-4a61-8b16-5068425dfdf9.png)

### This issue is complete when...

- [ ] Clicking on the hamburger icon results in a menu as seen in the design.
- [ ] Menu list items correctly link  to their destinations.
- [ ] The menu properly fits screens with width less than or equal to `768px`.

## Subtasks

- [ ] Wire up the hamburger menu
- [ ] Add relevant sections per design

**Comment by willm30** [comment]
CLOSE: #3518 MERGED.
