### ISSUE TITLE
Task feed events

### ISSUE THREAD

**Issue by collinvine** [JoinColony/colonyDapp#508]
wip

**Task activity events**
When we record a task activity event, it looks like this (this displays 3 events):

![screen shot 2018-10-18 at 2 01 07 pm](https://user-images.githubusercontent.com/15755488/47183996-52e34980-d2de-11e8-8d2f-877d4856ede6.png)

I think we have a list of events for this from the beta, but this can just be about design? I'll add events in a different spec.

- [ ] add the avatar of the user who created the event
- [ ] add event text
- [ ] add timestamp to right of activity event
- [ ] these should be aligned left

Some events may display other data, such as in this screenshot we have the `rating`. Do you need more specs for that? EDIT: specs for rating events #496
