### ISSUE TITLE
Wire up user wallet

### ISSUE THREAD

**Issue by karolinkas** [JoinColony/colonyDapp#588]
Besides wiring up the wallet wizard we want to wire the existing wallet. 
Keep in mind that this is a different admin then the Colony Admin, because it only relates to the user but might work similar. Transaction data surely comes from a blockchain integration, but maybe the user tokens get stored in the ddb as well?  

There's two main parts/tabs:
1. Transactions
2. ~Tokens~ see #748 

- [x] load all user's transactions history and replace existing mocks 
- [ ] ~load all user tokens~ see #748 
- [ ] ~allow disabling user tokens per user~ see #748 
- [ ] ~add new tokens to user tokens that get added from a list~ see #748
