### ISSUE TITLE
Add user inbox ddb address to profile

### ISSUE THREAD

**Issue by thiagodelgado111** [JoinColony/colonyDapp#646]
When we're creating the user profile, we should also create the inbox store and add it to the profile kvstore

## TODO

- [x] Create inbox store blueprint
- [x] Add store create/open function
- [x] Comment out user activity store creation
