### ISSUE TITLE
'Fetch task' data wiring

### ISSUE THREAD

**Issue by JamesLefrere** [JoinColony/colonyDapp#939]
Complete the data wiring for fetching a task (using the new payments workflow).

## TODOs

- [x] Remove all mocks for `Task`  and its child components
- [x] Create selector to get the task reference from the task route
- [x] Convert `Task` to a function so we can use hooks
- [x] Remove `Task.js` container (but keep `withDialog()`)
- [x] Create `taskFetcher` data fetcher
- [x] Use `taskFetcher` in `Task`
- [x] Use selectors for `Task` props
